export interface OrdenDeTrabajoCorrectiva{
    OrdenId?: number,
    FechaCreacion?: Date,
    EstadoId:number,
    TipoId:number,
    PrioridadId:number,
    OperarioId?:number,
    PersonaResponsable: string,  
    PersonaResponsableId?: number,     
    DescripcionCorrectivo:string,
    Resolucion?:string,
    Planta:number,
    Area?: number,
    Zona?:number,
    Seccion?:number,
    Codigo?:number,
    Grupo?:number,
    Equipo?:number,
    TituloCorrectivo: string,
    FechaPendiente?: string,
    FechaTerminado?: string
    FechaValidado?:string,
    UbicacionTecnica?: string,
    Localizacion?:string,
    Estado?:string,
    Tipo?:string,
    TiempoEmpleado?:number,
    Operario?:string,
    Prioridad?:string,
    Dias?:number,
}