export interface OrdenDeTrabajoPreventiva{
    OrdenId?: number,
    UbicacionTecnica?: string,
    EstadoId?:number,
    TipoId?:number,
    PrioridadId?:number,
    OperarioId?:number,
    Preventivo?: string,
    PersonaResponsable?: string,
    Planta:number,
    Area?: number,
    Zona?:number,
    Seccion?:number,
    Codigo?:number,
    Grupo?:number,
    Equipo?:string,
    ProximaRevision?: string,
    TiempoEmpleado?: string,
    FechaCreacion?: string,
    FechaPendiente?: string,
    FechaTerminado?: string,
    FechaValidado?:string,
    TituloCorrectivo?: string
    Localizacion?:string,
    Estado?:string,
    Tipo?:string,
    ComentarioResponsable?:string,
    Comentario?:string
    Operario?:string,
    Prioridad?:string,
    Dias?:number,
}