export interface OrdenDeTrabajo{
    OrdenId?: number,
    FechaCreacion?: string,
    EstadoId:number,
    TipoId?:number,
    PrioridadId:number,
    OperarioId?:number,
    PersonaResponsable?: number,    
    DescripcionCorrectivo?:string,
    Planta?:number,
    Area?: number,
    Zona?:number,
    Seccion?:number,
    Codigo?:number,
    Grupo?:number,
    Equipo?:number,
    TituloCorrectivo?: string,
    FechaPendiente?: string,
    FechaTerminado?: string
    FechaValidado?:string,
    UbicacionTecnica?: string,
    Localizacion?:string,
    Estado?:string,
    Tipo?:string,
    TiempoEmpleado?:number,
    Operario?:string,
    Prioridad?:string,
    Dias?:number,
    Preventivo?: string,
    ComentarioResponsable?:string,
    Comentario?:string
}